spring:
  application:
    name: ProductAutoComplete
  jpa:
    hibernate:
      ddl-auto: create-drop
  
logging:
  level:
    com:
      rippmn:
        product:
          web: DEBUG
          
    
  